#!/usr/bin/env python3
"""Draw Sightline's icon, at every size the platforms ask for.

    python3 scripts/make-icon.py

A glass prism with a line of sight through it. A beam enters at the lower left,
refracts inside the glass — the dashed segment, offset from the line it came in
on, because that is what refraction does — and leaves cleanly at the upper
right, ending on a focal point. The solid is drawn as an impossible figure: the
front beam of the triangle overlaps the rear face, so the eye reads a form that
cannot quite exist and keeps looking at it.

The mark is authored as SVG, which is the fourth thing tried here and the first
that is drawn rather than computed. Three earlier marks were built out of
primitives in this file — a crosshair of dots, a line with traces crossing it,
a slab with a lit seam — and each one lost to a shape that already meant
something else: a launcher, a sliders glyph, a runway. A drawing does not have
that problem, and the vector is the master rather than a copy kept in step with
one.

`magick` rasterises it. That is a build-time dependency of this script only, not
of the program; the icons it produces are committed.
"""

import struct
import subprocess
from io import BytesIO

from PIL import Image

FINAL = 1024
HERE = __file__.rsplit("/", 2)[0] + "/crates/gui/icons"

# The macOS rounded rectangle, as a fraction of the tile.
CORNER = 0.223

# The artwork is drawn on a 64-unit grid, sitting high and slightly left of
# centre. It is scaled and re-centred on its own bounding box rather than on the
# grid, so the margin around it is even.
ART_SCALE = 0.78
ART_CENTRE = (32, 28)

SVG = f"""<!-- Sightline. Generated by scripts/make-icon.py; edit that, not this. -->
<svg width="512" height="512" viewBox="0 0 64 64" fill="none"
     xmlns="http://www.w3.org/2000/svg">
  <defs>
    <!-- The band is clipped to the tile rather than drawn to fit it, so the
         angle is a property of the mark and the corners are a property of the
         platform. Changing either does not disturb the other. -->
    <clipPath id="tile">
      <rect width="64" height="64" rx="{64 * CORNER:.1f}"/>
    </clipPath>
  </defs>

  <!-- White, and one black diagonal running off both edges.

       Everything else this mark could be was tried: a crosshair, a slab with a
       lit seam, a glass prism refracting a beam, two interlocking solids that
       cannot both be in front. Each was a better drawing than this and a worse
       icon, and the reason is the same every time — they were legible at 512
       and a smudge at 48, which is the size that decides whether a person finds
       the window. An icon is recognised in a dock at a glance, not read.

       So: the one thing the name says, at the largest size it can be said. A
       line of sight, cut across the tile. It survives being shrunk to a
       favicon, it survives being greyed out, and it is the only mark here that
       could be drawn from memory by somebody who has seen it twice. -->
  <g clip-path="url(#tile)">
    <rect width="64" height="64" fill="#FFFFFF"/>
    <polygon points="75.31,-23.82 5.31,97.42 -11.31,87.82 58.69,-33.42" fill="#000000"/>
  </g>
</svg>
"""


def icns(path, img):
    """Write the macOS icon set.

    By hand, because no icns tool is installed on the machine this is built on
    and the alternative was leaving the file stale — which is the icon macOS
    would actually show, so the platform whose conventions this is drawn for
    would be the only one still shipping the old one.
    """
    kinds = [
        (b"ic07", 128), (b"ic08", 256), (b"ic09", 512), (b"ic10", 1024),
        (b"ic11", 32), (b"ic12", 64), (b"ic13", 256), (b"ic14", 512),
    ]
    chunks = []
    for kind, size in kinds:
        buf = BytesIO()
        img.resize((size, size), Image.LANCZOS).save(buf, format="PNG")
        data = buf.getvalue()
        chunks.append(kind + struct.pack(">I", len(data) + 8) + data)
    body = b"".join(chunks)
    open(path, "wb").write(b"icns" + struct.pack(">I", len(body) + 8) + body)


def build():
    open(f"{HERE}/icon.svg", "w").write(SVG)
    # `-background none`, or everything outside the rounded corners comes out
    # white and the icon sits in a square on any dock that is not the same
    # colour as this page.
    subprocess.run(
        ["magick", "-background", "none", f"{HERE}/icon.svg",
         "-resize", f"{FINAL}x{FINAL}", f"{HERE}/icon-master.png"],
        check=True,
    )
    img = Image.open(f"{HERE}/icon-master.png").convert("RGBA")
    # The tile is opaque now, so the corners are the thing to check: outside the
    # rounded rectangle must still be transparent, or the icon sits in a white
    # square on any dock that is not white.
    if img.getpixel((2, 2))[3] != 0:
        raise SystemExit("the corners came out opaque — check the clip path")
    if img.getpixel((FINAL // 2, 4))[3] == 0:
        raise SystemExit("the tile itself came out transparent — check the fill")

    for name, size in [("32x32.png", 32), ("128x128.png", 128),
                       ("128x128@2x.png", 256), ("icon.png", 512)]:
        img.resize((size, size), Image.LANCZOS).save(f"{HERE}/{name}")
    img.resize((256, 256), Image.LANCZOS).save(
        f"{HERE}/icon.ico", sizes=[(s, s) for s in (16, 24, 32, 48, 64, 128, 256)]
    )
    icns(f"{HERE}/icon.icns", img)
    print("wrote", HERE)


if __name__ == "__main__":
    build()
