#!/usr/bin/env python3
"""Draw Sightline's icon, at every size the platforms ask for.

    python3 scripts/make-icon.py

A glass prism with a line of sight through it. A beam enters at the lower left,
refracts inside the glass — the dashed segment, offset from the line it came in
on, because that is what refraction does — and leaves cleanly at the upper
right, ending on a focal point. The solid is drawn as an impossible figure: the
front beam of the triangle overlaps the rear face, so the eye reads a form that
cannot quite exist and keeps looking at it.

The mark is authored as SVG, which is the fourth thing tried here and the first
that is drawn rather than computed. Three earlier marks were built out of
primitives in this file — a crosshair of dots, a line with traces crossing it,
a slab with a lit seam — and each one lost to a shape that already meant
something else: a launcher, a sliders glyph, a runway. A drawing does not have
that problem, and the vector is the master rather than a copy kept in step with
one.

`magick` rasterises it. That is a build-time dependency of this script only, not
of the program; the icons it produces are committed.
"""

import struct
import subprocess
from io import BytesIO

from PIL import Image

FINAL = 1024
HERE = __file__.rsplit("/", 2)[0] + "/crates/gui/icons"

# The macOS rounded rectangle, as a fraction of the tile.
CORNER = 0.223

# The artwork is drawn on a 64-unit grid, sitting high and slightly left of
# centre. It is scaled and re-centred on its own bounding box rather than on the
# grid, so the margin around it is even.
ART_SCALE = 0.78
ART_CENTRE = (32, 28)

SVG = f"""<!-- Sightline. Generated by scripts/make-icon.py; edit that, not this. -->
<svg width="512" height="512" viewBox="0 0 64 64" fill="none"
     xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#17181c"/>
      <stop offset="1" stop-color="#08090b"/>
    </linearGradient>
    <!-- The line itself. Brighter where the light lands, falling away as the
         figure turns from it — which is the only way a drawing made of strokes
         can describe a solid. -->
    <linearGradient id="edge" x1="10%" y1="0%" x2="90%" y2="100%">
      <stop offset="0%" stop-color="#FFFFFF" stop-opacity="0.95"/>
      <stop offset="55%" stop-color="#FFFFFF" stop-opacity="0.62"/>
      <stop offset="100%" stop-color="#FFFFFF" stop-opacity="0.38"/>
    </linearGradient>
    <linearGradient id="beam" x1="0%" y1="100%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="#FFFFFF" stop-opacity="0.30"/>
      <stop offset="100%" stop-color="#FFFFFF" stop-opacity="0.9"/>
    </linearGradient>
    <!-- Barely there, and the reason the interior is not flat. -->
    <linearGradient id="face" x1="0%" y1="0%" x2="60%" y2="100%">
      <stop offset="0%" stop-color="#FFFFFF" stop-opacity="0.07"/>
      <stop offset="100%" stop-color="#FFFFFF" stop-opacity="0.012"/>
    </linearGradient>
  </defs>

  <rect width="64" height="64" rx="{64 * CORNER:.1f}" fill="url(#tile)"/>

  <g transform="translate(32 32) scale({ART_SCALE})
                translate({-ART_CENTRE[0]} {-ART_CENTRE[1]})"
     stroke="url(#edge)" stroke-linejoin="round" stroke-linecap="round"
     fill="none">

    <!-- Two solids sharing an edge, neither of which can be in front. The
         left reads as nearer along the shared edge and the right reads as
         nearer at its own corner, and the eye cannot settle which — which is
         the same trick the old prism used and the reason it kept being looked
         at.

         Drawn large and with few lines. The first version of this figure was
         accurate at 512 and a smudge at 64, which is the size that matters:
         an icon is a thing recognised in a dock at a glance, not a diagram
         read at leisure. Everything here is in service of surviving that. -->
    <path d="M 6 28 L 24 8 L 42 28 L 24 48 Z" fill="url(#face)" stroke-width="2.4"/>
    <path d="M 38 8 L 58 28 L 40 48 L 20 48 Z" fill="url(#face)" stroke-width="2.4"/>
    <!-- The shared edge last and at full strength, so the overlap is where the
         eye lands. -->
    <path d="M 24 48 L 42 28" stroke-width="2.4" stroke-opacity="1"/>

    <!-- Light in at the lower left, out at the upper right, both clear of the
         figure. In the first attempt they crossed the interior and read as
         more edges rather than as rays. -->
    <g stroke="url(#beam)" stroke-width="2">
      <path d="M -10 46 L 2 33"/>
      <path d="M -7 53 L 5 40"/>
      <path d="M 50 15 L 70 -4"/>
      <path d="M 55 22 L 75 3"/>
    </g>
  </g>
</svg>
"""


def icns(path, img):
    """Write the macOS icon set.

    By hand, because no icns tool is installed on the machine this is built on
    and the alternative was leaving the file stale — which is the icon macOS
    would actually show, so the platform whose conventions this is drawn for
    would be the only one still shipping the old one.
    """
    kinds = [
        (b"ic07", 128), (b"ic08", 256), (b"ic09", 512), (b"ic10", 1024),
        (b"ic11", 32), (b"ic12", 64), (b"ic13", 256), (b"ic14", 512),
    ]
    chunks = []
    for kind, size in kinds:
        buf = BytesIO()
        img.resize((size, size), Image.LANCZOS).save(buf, format="PNG")
        data = buf.getvalue()
        chunks.append(kind + struct.pack(">I", len(data) + 8) + data)
    body = b"".join(chunks)
    open(path, "wb").write(b"icns" + struct.pack(">I", len(body) + 8) + body)


def build():
    open(f"{HERE}/icon.svg", "w").write(SVG)
    # `-background none`, or everything outside the rounded corners comes out
    # white and the icon sits in a square on any dock that is not the same
    # colour as this page.
    subprocess.run(
        ["magick", "-background", "none", f"{HERE}/icon.svg",
         "-resize", f"{FINAL}x{FINAL}", f"{HERE}/icon-master.png"],
        check=True,
    )
    img = Image.open(f"{HERE}/icon-master.png").convert("RGBA")
    if img.getpixel((2, 2))[3] != 0:
        raise SystemExit("the corners came out opaque — check the rasteriser")

    for name, size in [("32x32.png", 32), ("128x128.png", 128),
                       ("128x128@2x.png", 256), ("icon.png", 512)]:
        img.resize((size, size), Image.LANCZOS).save(f"{HERE}/{name}")
    img.resize((256, 256), Image.LANCZOS).save(
        f"{HERE}/icon.ico", sizes=[(s, s) for s in (16, 24, 32, 48, 64, 128, 256)]
    )
    icns(f"{HERE}/icon.icns", img)
    print("wrote", HERE)


if __name__ == "__main__":
    build()
